   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE CLIENT';
      EXECUTE IMMEDIATE 'DROP SEQUENCE CLIENT_seq';

  EXCEPTION
      WHEN OTHERS THEN NULL;
  END;
  /
  CREATE SEQUENCE CLIENT_seq START WITH 1;
/
CREATE TABLE CLIENT (
  id INT DEFAULT CLIENT_seq.nextval  PRIMARY KEY,
  Name VARCHAR(250),
  Cpf VARCHAR(250) ,
  Adress VARCHAR(250),


);